# Generated by Django 4.2 on 2025-11-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_alter_submission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
